### ISSUE TITLE
[Enhancement] Releasing Mods from UE4 Editor.

### ISSUE THREAD

**Issue by aprilthepink** [modio/UE4Plugin#19]
It would be nice if a feature would be added that the mod could be directly cooked and uploaded to mod.io from the UE4 editor. Because I don't know how to implement an easier way for users to upload their models. (Currently I have to use an uggly method to import .fbx files which is uggly by the way

**Comment by Turupawn** [comment]
Yeah it would be nice to have a built-in integration for cooking from the editor. But unfortunately, we can't make a generic solution that works for all games because so far there is no standard in UE4. So every game can implement it in different ways.

Btw, have you joined our discord chat?
http://discord.mod.io
If you want to take a look, make sure you visit our #unreal channel, we have discussed some strategies regarding modding in UE4.

**Comment by MarkusRannare** [comment]
This is something that I want to take another look into after we have updated a few of our internal tools and projects. Hopefully it's something that I can start looking into sometime early next year

**Comment by brendenfrank** [comment]
I would model off of epic's SimpleUGC plugin. It's pretty much the standard for how to create mods in UE4. Putting that aside however, there are a few generic things I think should be included regardless:

- Authentication from within the editor whether by email or steam. Steam requires some source edits so perhaps by email.
- Re-enable the mod.io toolbar button and allow a user to upload a mod under their above authenticated account.
- Allow a selected directory to be packaged into a zip and uploaded under a specified mod id.

I think users could customize that further, but it would have saved us a lot of time.

**Comment by MarkusRannare** [comment]
We are working on a rewrite of the Plugin that we plan to include this in. Sadly it won't get into this version of the plugin. I'll save you feedback for the next version of the plugin so that we can ensure that we take it into the consideration during the planning
